version: "2"
linters:
  default: none
  enable:
    # Core linters for critical issues (already enabled in main config)
    - bodyclose
    - errorlint
    - misspell
    - prealloc
    - wrapcheck
    - forbidigo
    - wsl_v5

    # Additional linters for code quality (warnings)
    - gocritic # Critical code analysis
    - gocyclo # Cyclomatic complexity
    - goconst # Find magic constants
    - gocognit # Cognitive complexity
    - gosec # Security
    - govet # Standard Go checks
    - ineffassign # Ineffective assignments
    - nakedret # Naked returns
    - noctx # Missing context
    - nolintlint # Validate nolint directives
    - revive # Extended linter
    - staticcheck # Static analysis
    - unconvert # Unnecessary conversions
    - unparam # Unused parameters
    - unused # Unused code
    - whitespace # Whitespace
    - wsl_v5 # Empty lines
    - dupl # Code duplication
    - funlen # Function length
    - gochecknoinits # Check init functions
    - gocognit # Cognitive complexity
    - godot # Period at end of comments
    - godox # TODO/FIXME comments

    - mnd # Magic numbers (replacement for gomnd)
    - gomodguard # Module guard
    - lll # Line length
    - nestif # Nested if
    - nlreturn # Newlines around return
    - rowserrcheck # Rows error check
    - sqlclosecheck # SQL connections closing
    - testpackage # Test packages
    - varnamelen # Variable name length

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    gocyclo:
      min-complexity: 10
    mnd:
      settings:
        # Ignore numbers 0, 1, 2, 3, 4, 5, 10, 100, 1000
        ignored-numbers: "0,1,2,3,4,5,10,100,1000"
        ignored-functions: "strings.Split,strings.SplitN,strings.SplitAfter,strings.SplitAfterN"
    gosec:
      config:
        G306: "0666"
    revive:
      confidence: 0.8
      enable-all-rules: true
      rules:
        - name: function-length
          arguments:
            - 30 # Stricter for warnings
            - 0
          severity: warning
          disabled: false
        - name: function-result-limit
          arguments:
            - 3
          severity: warning
          disabled: false
        - name: cognitive-complexity
          arguments:
            - 15 # Stricter for warnings
          severity: warning
          disabled: false
        - name: cyclomatic
          arguments:
            - 8 # Stricter for warnings
          severity: warning
          disabled: false
        - name: line-length-limit
          arguments:
            - 100 # Stricter for warnings
          severity: warning
          disabled: false
        - name: argument-limit
          arguments:
            - 5 # Stricter for warnings
          severity: warning
          disabled: false
        - name: unhandled-error
          arguments:
            - bytes\.Buffer\.Write.*
            - strings\.Builder\.Write.*
          disabled: false
        - name: comment-spacings
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: banned-characters
          disabled: true
        - name: file-header
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: struct-tag
          disabled: true
        - name: add-constant
          disabled: true
        - name: empty-lines
          disabled: true
    funlen:
      lines: 50
      statements: 30
    lll:
      line-length: 100
    nestif:
      min-complexity: 5
    varnamelen:
      min-name-length: 2
      ignore-names: "i,j,k,v,ok,err,id,db,ui,ui16,ui32,ui64,ui8,uri,url,uid,pid,ip,id,ui,ui16,ui32,ui64,ui8,uri,url,uid,pid,ip"
    gomodguard:
      allowed:
        modules: []
        domains: []
      blocked:
        modules: []
        versions: []

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - wrapcheck
          - wsl_v5
          - lll
          - funlen
          - gocyclo
          - gocognit
          - nestif
          - revive
        path: (.+)_test.go
      - linters:
          - wsl_v5
          - dupl
          - funlen
          - gocyclo
          - gocognit
          - revive
        path: (.+).pb.go
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: internal/types/types.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/transport/http/gen

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/transport/http/gen
