# golangci-lint configuration for Keyper
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  go: "1.23"

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false  # Report all issues, not just new ones
  fix: false

  exclude-dirs:
    - api/openapi
    - vendor

  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.pb\\.gw\\.go$"
    - ".*_grpc\\.pb\\.go$"

linters:
  disable-all: true
  enable:
    # Defaults from standard set
    - errcheck      # Unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Checks for unused code

    # Additional code quality
    - gofmt         # Formats code
    - goimports     # Manages imports
    - misspell      # Spelling mistakes
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - gocyclo       # Cyclomatic complexity
    - goconst       # Repeated strings that could be constants
    - gosec         # Security issues (critical for password manager)
    - bodyclose     # HTTP response body must be closed
    - noctx         # Detect sending HTTP requests without context.Context

    # Style and best practices
    - godot         # Check if comments end in a period
    - gofumpt       # Stricter gofmt
    - whitespace    # Detects leading and trailing whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      # Common functions where errors can be safely ignored
      - io.Copy(*bytes.Buffer)
      - (*database/sql.Rows).Close
      - (*os.File).Close

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)
    config:
      G101:
        # Pattern for detecting hardcoded credentials
        pattern: "(?i)passwd|pass|password|pwd|secret|token|key|apiKey|api_key|bearer|cred|auth"
        ignore_entropy: false
        entropy_threshold: "80.0"
        per_char_threshold: "3.0"
        truncate: "32"

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true

  gofumpt:
    extra-rules: true

  goimports:
    local-prefixes: github.com/koyif/keyper

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  misspell:
    locale: US

  staticcheck:
    checks:
      - all

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - goconst

    # Exclude linters for generated proto files (belt and suspenders with skip-files)
    - path: ".*\\.pb\\.go$"
      linters:
        - all
    - path: ".*\\.pb\\.gw\\.go$"
      linters:
        - all
    - path: ".*_grpc\\.pb\\.go$"
      linters:
        - all

    # Allow main functions to be complex
    - path: cmd/
      text: "cyclomatic complexity"
      linters:
        - gocyclo

    # Crypto package may have legitimate complexity
    - path: internal/crypto/
      linters:
        - gocyclo
