version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errorlint
    - forbidigo
    - misspell
    - nestif
    - prealloc
    - wrapcheck
    - whitespace
    - wsl_v5
    - rowserrcheck
    - gomodguard
    - unconvert
    - nakedret
    - noctx
    - gosec
  settings:
    forbidigo:
      forbid:
        - pattern: (?i)(^|\.)print(f|ln)?$
    gomoddirectives:
      replace-local: true
    gosec:
      config:
        G306: "0666"
    revive:
      confidence: 0.8
      enable-all-rules: true
      rules:
        - name: function-length
          arguments:
            - 50
            - 0
          severity: warning
          disabled: false
        - name: function-result-limit
          arguments:
            - 3
          severity: warning
          disabled: false
        - name: cognitive-complexity
          arguments:
            - 20
          severity: warning
          disabled: false
        - name: cyclomatic
          arguments:
            - 10
          severity: warning
          disabled: false
        - name: line-length-limit
          arguments:
            - 110
          severity: warning
          disabled: false
        - name: argument-limit
          arguments:
            - 6
          severity: warning
          disabled: false
        - name: unhandled-error
          arguments:
            - bytes\.Buffer\.Write.*
            - strings\.Builder\.Write.*
          disabled: false
        - name: comment-spacings
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: banned-characters
          disabled: true
        - name: file-header
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: struct-tag
          disabled: true
        - name: add-constant
          disabled: true
        - name: empty-lines
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - wrapcheck
          - wsl_v5
        path: (.+)_test.go
      - linters:
          - wsl_v5
        path: (.+).pb.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/transport/http/gen
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
