# GoReleaser configuration for Keyper
# https://goreleaser.com

version: 2

before:
  hooks:
    # Install dependencies
    - go mod download
    - go mod tidy

builds:
  # Client binary
  - id: keyper-client
    main: ./cmd/client
    binary: keyper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Don't build darwin/386
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}
    flags:
      - -trimpath
    mod_timestamp: "{{.CommitTimestamp}}"

  # Server binary
  - id: keyper-server
    main: ./cmd/server
    binary: keyper-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Don't build darwin/386
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}
    flags:
      - -trimpath
    mod_timestamp: "{{.CommitTimestamp}}"

archives:
  - id: keyper
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - docs/*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other Changes"
      order: 999

# Enable binary signing (requires GPG key)
signs:
  - cmd: gpg
    args:
      - --output
      - $signature
      - --detach-sig
      - $artifact
    signature: ${artifact}.sig
    artifacts: checksum

release:
  github:
    owner: koyif
    name: keyper
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Keyper {{ .Version }}

    Download the appropriate binary for your platform below.

    ### Installation

    **Linux/macOS:**
    ```bash
    curl -sSL https://raw.githubusercontent.com/koyif/keyper/main/scripts/install.sh | bash
    ```

    **Windows (PowerShell):**
    ```powershell
    iwr https://raw.githubusercontent.com/koyif/keyper/main/scripts/install.ps1 -useb | iex
    ```

    Or download the binary directly from the assets below.
  footer: |
    **Full Changelog**: https://github.com/koyif/keyper/compare/{{ .PreviousTag }}...{{ .Tag }}

    **Verify checksums:**
    ```bash
    sha256sum -c keyper_{{ .Version }}_checksums.txt
    ```