// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: secrets.proto

package proto

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateSecretRequest contains data for creating a new secret
type CreateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SecretType             `protobuf:"varint,1,opt,name=type,proto3,enum=keyper.api.v1.SecretType" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	EncryptedData string                 `protobuf:"bytes,3,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"` // Client-encrypted payload
	Metadata      *Metadata              `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_secrets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSecretRequest) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *CreateSecretRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSecretRequest) GetEncryptedData() string {
	if x != nil {
		return x.EncryptedData
	}
	return ""
}

func (x *CreateSecretRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CreateSecretResponse contains the created secret
type CreateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_secrets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateSecretResponse) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *CreateSecretResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetSecretRequest contains the secret ID to retrieve
type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_secrets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{2}
}

func (x *GetSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

// GetSecretResponse contains the requested secret
type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_secrets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{3}
}

func (x *GetSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

// UpdateSecretRequest contains updated secret data
type UpdateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	EncryptedData string                 `protobuf:"bytes,3,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"` // Client-encrypted payload
	Metadata      *Metadata              `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"` // For optimistic locking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_secrets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *UpdateSecretRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateSecretRequest) GetEncryptedData() string {
	if x != nil {
		return x.EncryptedData
	}
	return ""
}

func (x *UpdateSecretRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateSecretRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// UpdateSecretResponse contains the updated secret
type UpdateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretResponse) Reset() {
	*x = UpdateSecretResponse{}
	mi := &file_secrets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretResponse) ProtoMessage() {}

func (x *UpdateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretResponse.ProtoReflect.Descriptor instead.
func (*UpdateSecretResponse) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *UpdateSecretResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DeleteSecretRequest contains the secret ID to delete
type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_secrets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

// DeleteSecretResponse confirms deletion
type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_secrets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSecretResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListSecretsRequest contains optional filtering parameters
type ListSecretsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           SecretType             `protobuf:"varint,1,opt,name=type,proto3,enum=keyper.api.v1.SecretType" json:"type,omitempty"`             // Filter by type (optional)
	Category       string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`                                    // Filter by category (optional)
	IncludeDeleted bool                   `protobuf:"varint,3,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"` // Include soft-deleted secrets
	PageSize       int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                   // Pagination
	PageToken      string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`                 // Pagination token
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_secrets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{8}
}

func (x *ListSecretsRequest) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *ListSecretsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListSecretsRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

func (x *ListSecretsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSecretsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListSecretsResponse contains the list of secrets
type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*Secret              `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_secrets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{9}
}

func (x *ListSecretsResponse) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *ListSecretsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListSecretsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// SearchSecretsRequest contains search criteria
type SearchSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                       // Search term (searches title, tags, notes)
	Type          SecretType             `protobuf:"varint,2,opt,name=type,proto3,enum=keyper.api.v1.SecretType" json:"type,omitempty"`          // Filter by type (optional)
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`                                 // Filter by category (optional)
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`                                         // Filter by tags (optional)
	FavoritesOnly bool                   `protobuf:"varint,5,opt,name=favorites_only,json=favoritesOnly,proto3" json:"favorites_only,omitempty"` // Only return favorites
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSecretsRequest) Reset() {
	*x = SearchSecretsRequest{}
	mi := &file_secrets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSecretsRequest) ProtoMessage() {}

func (x *SearchSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSecretsRequest.ProtoReflect.Descriptor instead.
func (*SearchSecretsRequest) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{10}
}

func (x *SearchSecretsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchSecretsRequest) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *SearchSecretsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SearchSecretsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchSecretsRequest) GetFavoritesOnly() bool {
	if x != nil {
		return x.FavoritesOnly
	}
	return false
}

// SearchSecretsResponse contains matching secrets
type SearchSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*Secret              `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSecretsResponse) Reset() {
	*x = SearchSecretsResponse{}
	mi := &file_secrets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSecretsResponse) ProtoMessage() {}

func (x *SearchSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSecretsResponse.ProtoReflect.Descriptor instead.
func (*SearchSecretsResponse) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{11}
}

func (x *SearchSecretsResponse) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *SearchSecretsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_secrets_proto protoreflect.FileDescriptor

const file_secrets_proto_rawDesc = "" +
	"\n" +
	"\rsecrets.proto\x12\rkeyper.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fmodels.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb6\x01\n" +
	"\x13CreateSecretRequest\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.keyper.api.v1.SecretTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\x0eencrypted_data\x18\x03 \x01(\tR\rencryptedData\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.keyper.api.v1.MetadataR\bmetadata\"_\n" +
	"\x14CreateSecretResponse\x12-\n" +
	"\x06secret\x18\x01 \x01(\v2\x15.keyper.api.v1.SecretR\x06secret\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x10GetSecretRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\"B\n" +
	"\x11GetSecretResponse\x12-\n" +
	"\x06secret\x18\x01 \x01(\v2\x15.keyper.api.v1.SecretR\x06secret\"\xbe\x01\n" +
	"\x13UpdateSecretRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\x0eencrypted_data\x18\x03 \x01(\tR\rencryptedData\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.keyper.api.v1.MetadataR\bmetadata\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\"_\n" +
	"\x14UpdateSecretResponse\x12-\n" +
	"\x06secret\x18\x01 \x01(\v2\x15.keyper.api.v1.SecretR\x06secret\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\x13DeleteSecretRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\"0\n" +
	"\x14DeleteSecretResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xc4\x01\n" +
	"\x12ListSecretsRequest\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.keyper.api.v1.SecretTypeR\x04type\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12'\n" +
	"\x0finclude_deleted\x18\x03 \x01(\bR\x0eincludeDeleted\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x8f\x01\n" +
	"\x13ListSecretsResponse\x12/\n" +
	"\asecrets\x18\x01 \x03(\v2\x15.keyper.api.v1.SecretR\asecrets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xb2\x01\n" +
	"\x14SearchSecretsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.keyper.api.v1.SecretTypeR\x04type\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12%\n" +
	"\x0efavorites_only\x18\x05 \x01(\bR\rfavoritesOnly\"i\n" +
	"\x15SearchSecretsResponse\x12/\n" +
	"\asecrets\x18\x01 \x03(\v2\x15.keyper.api.v1.SecretR\asecrets\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount2\xe5\x06\n" +
	"\x0eSecretsService\x12o\n" +
	"\fCreateSecret\x12\".keyper.api.v1.CreateSecretRequest\x1a#.keyper.api.v1.CreateSecretResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/secrets\x12o\n" +
	"\tGetSecret\x12\x1f.keyper.api.v1.GetSecretRequest\x1a .keyper.api.v1.GetSecretResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/secrets/{secret_id}\x12{\n" +
	"\fUpdateSecret\x12\".keyper.api.v1.UpdateSecretRequest\x1a#.keyper.api.v1.UpdateSecretResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/v1/secrets/{secret_id}\x12x\n" +
	"\fDeleteSecret\x12\".keyper.api.v1.DeleteSecretRequest\x1a#.keyper.api.v1.DeleteSecretResponse\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1/secrets/{secret_id}\x12i\n" +
	"\vListSecrets\x12!.keyper.api.v1.ListSecretsRequest\x1a\".keyper.api.v1.ListSecretsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/secrets\x12v\n" +
	"\rSearchSecrets\x12#.keyper.api.v1.SearchSecretsRequest\x1a$.keyper.api.v1.SearchSecretsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/secrets/search\x1a\x96\x01\x92A\x92\x01\x12\x8f\x01CRUD operations for encrypted secrets. All endpoints require authentication. Secrets are encrypted client-side using AES-256-GCM before upload.B-Z+github.com/koyif/keyper/pkg/api/proto;protob\x06proto3"

var (
	file_secrets_proto_rawDescOnce sync.Once
	file_secrets_proto_rawDescData []byte
)

func file_secrets_proto_rawDescGZIP() []byte {
	file_secrets_proto_rawDescOnce.Do(func() {
		file_secrets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secrets_proto_rawDesc), len(file_secrets_proto_rawDesc)))
	})
	return file_secrets_proto_rawDescData
}

var file_secrets_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_secrets_proto_goTypes = []any{
	(*CreateSecretRequest)(nil),   // 0: keyper.api.v1.CreateSecretRequest
	(*CreateSecretResponse)(nil),  // 1: keyper.api.v1.CreateSecretResponse
	(*GetSecretRequest)(nil),      // 2: keyper.api.v1.GetSecretRequest
	(*GetSecretResponse)(nil),     // 3: keyper.api.v1.GetSecretResponse
	(*UpdateSecretRequest)(nil),   // 4: keyper.api.v1.UpdateSecretRequest
	(*UpdateSecretResponse)(nil),  // 5: keyper.api.v1.UpdateSecretResponse
	(*DeleteSecretRequest)(nil),   // 6: keyper.api.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),  // 7: keyper.api.v1.DeleteSecretResponse
	(*ListSecretsRequest)(nil),    // 8: keyper.api.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),   // 9: keyper.api.v1.ListSecretsResponse
	(*SearchSecretsRequest)(nil),  // 10: keyper.api.v1.SearchSecretsRequest
	(*SearchSecretsResponse)(nil), // 11: keyper.api.v1.SearchSecretsResponse
	(SecretType)(0),               // 12: keyper.api.v1.SecretType
	(*Metadata)(nil),              // 13: keyper.api.v1.Metadata
	(*Secret)(nil),                // 14: keyper.api.v1.Secret
}
var file_secrets_proto_depIdxs = []int32{
	12, // 0: keyper.api.v1.CreateSecretRequest.type:type_name -> keyper.api.v1.SecretType
	13, // 1: keyper.api.v1.CreateSecretRequest.metadata:type_name -> keyper.api.v1.Metadata
	14, // 2: keyper.api.v1.CreateSecretResponse.secret:type_name -> keyper.api.v1.Secret
	14, // 3: keyper.api.v1.GetSecretResponse.secret:type_name -> keyper.api.v1.Secret
	13, // 4: keyper.api.v1.UpdateSecretRequest.metadata:type_name -> keyper.api.v1.Metadata
	14, // 5: keyper.api.v1.UpdateSecretResponse.secret:type_name -> keyper.api.v1.Secret
	12, // 6: keyper.api.v1.ListSecretsRequest.type:type_name -> keyper.api.v1.SecretType
	14, // 7: keyper.api.v1.ListSecretsResponse.secrets:type_name -> keyper.api.v1.Secret
	12, // 8: keyper.api.v1.SearchSecretsRequest.type:type_name -> keyper.api.v1.SecretType
	14, // 9: keyper.api.v1.SearchSecretsResponse.secrets:type_name -> keyper.api.v1.Secret
	0,  // 10: keyper.api.v1.SecretsService.CreateSecret:input_type -> keyper.api.v1.CreateSecretRequest
	2,  // 11: keyper.api.v1.SecretsService.GetSecret:input_type -> keyper.api.v1.GetSecretRequest
	4,  // 12: keyper.api.v1.SecretsService.UpdateSecret:input_type -> keyper.api.v1.UpdateSecretRequest
	6,  // 13: keyper.api.v1.SecretsService.DeleteSecret:input_type -> keyper.api.v1.DeleteSecretRequest
	8,  // 14: keyper.api.v1.SecretsService.ListSecrets:input_type -> keyper.api.v1.ListSecretsRequest
	10, // 15: keyper.api.v1.SecretsService.SearchSecrets:input_type -> keyper.api.v1.SearchSecretsRequest
	1,  // 16: keyper.api.v1.SecretsService.CreateSecret:output_type -> keyper.api.v1.CreateSecretResponse
	3,  // 17: keyper.api.v1.SecretsService.GetSecret:output_type -> keyper.api.v1.GetSecretResponse
	5,  // 18: keyper.api.v1.SecretsService.UpdateSecret:output_type -> keyper.api.v1.UpdateSecretResponse
	7,  // 19: keyper.api.v1.SecretsService.DeleteSecret:output_type -> keyper.api.v1.DeleteSecretResponse
	9,  // 20: keyper.api.v1.SecretsService.ListSecrets:output_type -> keyper.api.v1.ListSecretsResponse
	11, // 21: keyper.api.v1.SecretsService.SearchSecrets:output_type -> keyper.api.v1.SearchSecretsResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_secrets_proto_init() }
func file_secrets_proto_init() {
	if File_secrets_proto != nil {
		return
	}
	file_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secrets_proto_rawDesc), len(file_secrets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secrets_proto_goTypes,
		DependencyIndexes: file_secrets_proto_depIdxs,
		MessageInfos:      file_secrets_proto_msgTypes,
	}.Build()
	File_secrets_proto = out.File
	file_secrets_proto_goTypes = nil
	file_secrets_proto_depIdxs = nil
}
