// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: sync.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConflictType defines the type of sync conflict
type ConflictType int32

const (
	ConflictType_CONFLICT_TYPE_UNSPECIFIED       ConflictType = 0
	ConflictType_CONFLICT_TYPE_MODIFIED_MODIFIED ConflictType = 1 // Both client and server modified
	ConflictType_CONFLICT_TYPE_MODIFIED_DELETED  ConflictType = 2 // Client modified, server deleted
	ConflictType_CONFLICT_TYPE_DELETED_MODIFIED  ConflictType = 3 // Client deleted, server modified
	ConflictType_CONFLICT_TYPE_VERSION_MISMATCH  ConflictType = 4 // Version tracking mismatch
)

// Enum value maps for ConflictType.
var (
	ConflictType_name = map[int32]string{
		0: "CONFLICT_TYPE_UNSPECIFIED",
		1: "CONFLICT_TYPE_MODIFIED_MODIFIED",
		2: "CONFLICT_TYPE_MODIFIED_DELETED",
		3: "CONFLICT_TYPE_DELETED_MODIFIED",
		4: "CONFLICT_TYPE_VERSION_MISMATCH",
	}
	ConflictType_value = map[string]int32{
		"CONFLICT_TYPE_UNSPECIFIED":       0,
		"CONFLICT_TYPE_MODIFIED_MODIFIED": 1,
		"CONFLICT_TYPE_MODIFIED_DELETED":  2,
		"CONFLICT_TYPE_DELETED_MODIFIED":  3,
		"CONFLICT_TYPE_VERSION_MISMATCH":  4,
	}
)

func (x ConflictType) Enum() *ConflictType {
	p := new(ConflictType)
	*p = x
	return p
}

func (x ConflictType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConflictType) Descriptor() protoreflect.EnumDescriptor {
	return file_sync_proto_enumTypes[0].Descriptor()
}

func (ConflictType) Type() protoreflect.EnumType {
	return &file_sync_proto_enumTypes[0]
}

func (x ConflictType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConflictType.Descriptor instead.
func (ConflictType) EnumDescriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

// PullRequest requests changes since a specific version
type PullRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LastSyncVersion int64                  `protobuf:"varint,1,opt,name=last_sync_version,json=lastSyncVersion,proto3" json:"last_sync_version,omitempty"` // Last known version on client
	LastSyncTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *PullRequest) GetLastSyncVersion() int64 {
	if x != nil {
		return x.LastSyncVersion
	}
	return 0
}

func (x *PullRequest) GetLastSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncTime
	}
	return nil
}

// PullResponse contains changes from the server
type PullResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Secrets          []*Secret              `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`                                             // All changed/new secrets
	DeletedSecretIds []string               `protobuf:"bytes,2,rep,name=deleted_secret_ids,json=deletedSecretIds,proto3" json:"deleted_secret_ids,omitempty"` // IDs of deleted secrets
	CurrentVersion   int64                  `protobuf:"varint,3,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`        // Server's current version
	SyncTime         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"`
	HasConflicts     bool                   `protobuf:"varint,5,opt,name=has_conflicts,json=hasConflicts,proto3" json:"has_conflicts,omitempty"`
	Conflicts        []*Conflict            `protobuf:"bytes,6,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PullResponse) Reset() {
	*x = PullResponse{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResponse) ProtoMessage() {}

func (x *PullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResponse.ProtoReflect.Descriptor instead.
func (*PullResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *PullResponse) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *PullResponse) GetDeletedSecretIds() []string {
	if x != nil {
		return x.DeletedSecretIds
	}
	return nil
}

func (x *PullResponse) GetCurrentVersion() int64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *PullResponse) GetSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncTime
	}
	return nil
}

func (x *PullResponse) GetHasConflicts() bool {
	if x != nil {
		return x.HasConflicts
	}
	return false
}

func (x *PullResponse) GetConflicts() []*Conflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

// PushRequest sends local changes to server
type PushRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Secrets          []*Secret              `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`                                             // New or modified secrets
	DeletedSecretIds []string               `protobuf:"bytes,2,rep,name=deleted_secret_ids,json=deletedSecretIds,proto3" json:"deleted_secret_ids,omitempty"` // IDs to delete
	BaseVersion      int64                  `protobuf:"varint,3,opt,name=base_version,json=baseVersion,proto3" json:"base_version,omitempty"`                 // Version client is based on
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2}
}

func (x *PushRequest) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *PushRequest) GetDeletedSecretIds() []string {
	if x != nil {
		return x.DeletedSecretIds
	}
	return nil
}

func (x *PushRequest) GetBaseVersion() int64 {
	if x != nil {
		return x.BaseVersion
	}
	return 0
}

// PushResponse confirms changes accepted by server
type PushResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NewVersion        int64                  `protobuf:"varint,1,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"` // New version after push
	SyncTime          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"`
	AcceptedSecretIds []string               `protobuf:"bytes,3,rep,name=accepted_secret_ids,json=acceptedSecretIds,proto3" json:"accepted_secret_ids,omitempty"`
	Conflicts         []*Conflict            `protobuf:"bytes,4,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	Message           string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{3}
}

func (x *PushResponse) GetNewVersion() int64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

func (x *PushResponse) GetSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncTime
	}
	return nil
}

func (x *PushResponse) GetAcceptedSecretIds() []string {
	if x != nil {
		return x.AcceptedSecretIds
	}
	return nil
}

func (x *PushResponse) GetConflicts() []*Conflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *PushResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetSyncStatusRequest requests current sync status
type GetSyncStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncStatusRequest) Reset() {
	*x = GetSyncStatusRequest{}
	mi := &file_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncStatusRequest) ProtoMessage() {}

func (x *GetSyncStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSyncStatusRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{4}
}

// GetSyncStatusResponse contains sync metadata
type GetSyncStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerVersion  int64                  `protobuf:"varint,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	LastSyncTime   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	TotalSecrets   int32                  `protobuf:"varint,3,opt,name=total_secrets,json=totalSecrets,proto3" json:"total_secrets,omitempty"`
	PendingChanges int32                  `protobuf:"varint,4,opt,name=pending_changes,json=pendingChanges,proto3" json:"pending_changes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSyncStatusResponse) Reset() {
	*x = GetSyncStatusResponse{}
	mi := &file_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncStatusResponse) ProtoMessage() {}

func (x *GetSyncStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSyncStatusResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{5}
}

func (x *GetSyncStatusResponse) GetServerVersion() int64 {
	if x != nil {
		return x.ServerVersion
	}
	return 0
}

func (x *GetSyncStatusResponse) GetLastSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncTime
	}
	return nil
}

func (x *GetSyncStatusResponse) GetTotalSecrets() int32 {
	if x != nil {
		return x.TotalSecrets
	}
	return 0
}

func (x *GetSyncStatusResponse) GetPendingChanges() int32 {
	if x != nil {
		return x.PendingChanges
	}
	return 0
}

// Conflict represents a sync conflict
type Conflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Type          ConflictType           `protobuf:"varint,2,opt,name=type,proto3,enum=keyper.api.v1.ConflictType" json:"type,omitempty"`
	ServerVersion *Secret                `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	ClientVersion *Secret                `protobuf:"bytes,4,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{6}
}

func (x *Conflict) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *Conflict) GetType() ConflictType {
	if x != nil {
		return x.Type
	}
	return ConflictType_CONFLICT_TYPE_UNSPECIFIED
}

func (x *Conflict) GetServerVersion() *Secret {
	if x != nil {
		return x.ServerVersion
	}
	return nil
}

func (x *Conflict) GetClientVersion() *Secret {
	if x != nil {
		return x.ClientVersion
	}
	return nil
}

func (x *Conflict) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\rkeyper.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fmodels.proto\"{\n" +
	"\vPullRequest\x12*\n" +
	"\x11last_sync_version\x18\x01 \x01(\x03R\x0flastSyncVersion\x12@\n" +
	"\x0elast_sync_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncTime\"\xab\x02\n" +
	"\fPullResponse\x12/\n" +
	"\asecrets\x18\x01 \x03(\v2\x15.keyper.api.v1.SecretR\asecrets\x12,\n" +
	"\x12deleted_secret_ids\x18\x02 \x03(\tR\x10deletedSecretIds\x12'\n" +
	"\x0fcurrent_version\x18\x03 \x01(\x03R\x0ecurrentVersion\x127\n" +
	"\tsync_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bsyncTime\x12#\n" +
	"\rhas_conflicts\x18\x05 \x01(\bR\fhasConflicts\x125\n" +
	"\tconflicts\x18\x06 \x03(\v2\x17.keyper.api.v1.ConflictR\tconflicts\"\x8f\x01\n" +
	"\vPushRequest\x12/\n" +
	"\asecrets\x18\x01 \x03(\v2\x15.keyper.api.v1.SecretR\asecrets\x12,\n" +
	"\x12deleted_secret_ids\x18\x02 \x03(\tR\x10deletedSecretIds\x12!\n" +
	"\fbase_version\x18\x03 \x01(\x03R\vbaseVersion\"\xe9\x01\n" +
	"\fPushResponse\x12\x1f\n" +
	"\vnew_version\x18\x01 \x01(\x03R\n" +
	"newVersion\x127\n" +
	"\tsync_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bsyncTime\x12.\n" +
	"\x13accepted_secret_ids\x18\x03 \x03(\tR\x11acceptedSecretIds\x125\n" +
	"\tconflicts\x18\x04 \x03(\v2\x17.keyper.api.v1.ConflictR\tconflicts\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x16\n" +
	"\x14GetSyncStatusRequest\"\xce\x01\n" +
	"\x15GetSyncStatusResponse\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\x03R\rserverVersion\x12@\n" +
	"\x0elast_sync_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncTime\x12#\n" +
	"\rtotal_secrets\x18\x03 \x01(\x05R\ftotalSecrets\x12'\n" +
	"\x0fpending_changes\x18\x04 \x01(\x05R\x0ependingChanges\"\xf6\x01\n" +
	"\bConflict\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.keyper.api.v1.ConflictTypeR\x04type\x12<\n" +
	"\x0eserver_version\x18\x03 \x01(\v2\x15.keyper.api.v1.SecretR\rserverVersion\x12<\n" +
	"\x0eclient_version\x18\x04 \x01(\v2\x15.keyper.api.v1.SecretR\rclientVersion\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription*\xbe\x01\n" +
	"\fConflictType\x12\x1d\n" +
	"\x19CONFLICT_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fCONFLICT_TYPE_MODIFIED_MODIFIED\x10\x01\x12\"\n" +
	"\x1eCONFLICT_TYPE_MODIFIED_DELETED\x10\x02\x12\"\n" +
	"\x1eCONFLICT_TYPE_DELETED_MODIFIED\x10\x03\x12\"\n" +
	"\x1eCONFLICT_TYPE_VERSION_MISMATCH\x10\x042\xb8\x02\n" +
	"\vSyncService\x12Y\n" +
	"\x04Pull\x12\x1a.keyper.api.v1.PullRequest\x1a\x1b.keyper.api.v1.PullResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/sync/pull\x12Y\n" +
	"\x04Push\x12\x1a.keyper.api.v1.PushRequest\x1a\x1b.keyper.api.v1.PushResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/sync/push\x12s\n" +
	"\rGetSyncStatus\x12#.keyper.api.v1.GetSyncStatusRequest\x1a$.keyper.api.v1.GetSyncStatusResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/sync/statusB+Z)github.com/koy/keyper/pkg/api/proto;protob\x06proto3"

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData []byte
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)))
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sync_proto_goTypes = []any{
	(ConflictType)(0),             // 0: keyper.api.v1.ConflictType
	(*PullRequest)(nil),           // 1: keyper.api.v1.PullRequest
	(*PullResponse)(nil),          // 2: keyper.api.v1.PullResponse
	(*PushRequest)(nil),           // 3: keyper.api.v1.PushRequest
	(*PushResponse)(nil),          // 4: keyper.api.v1.PushResponse
	(*GetSyncStatusRequest)(nil),  // 5: keyper.api.v1.GetSyncStatusRequest
	(*GetSyncStatusResponse)(nil), // 6: keyper.api.v1.GetSyncStatusResponse
	(*Conflict)(nil),              // 7: keyper.api.v1.Conflict
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*Secret)(nil),                // 9: keyper.api.v1.Secret
}
var file_sync_proto_depIdxs = []int32{
	8,  // 0: keyper.api.v1.PullRequest.last_sync_time:type_name -> google.protobuf.Timestamp
	9,  // 1: keyper.api.v1.PullResponse.secrets:type_name -> keyper.api.v1.Secret
	8,  // 2: keyper.api.v1.PullResponse.sync_time:type_name -> google.protobuf.Timestamp
	7,  // 3: keyper.api.v1.PullResponse.conflicts:type_name -> keyper.api.v1.Conflict
	9,  // 4: keyper.api.v1.PushRequest.secrets:type_name -> keyper.api.v1.Secret
	8,  // 5: keyper.api.v1.PushResponse.sync_time:type_name -> google.protobuf.Timestamp
	7,  // 6: keyper.api.v1.PushResponse.conflicts:type_name -> keyper.api.v1.Conflict
	8,  // 7: keyper.api.v1.GetSyncStatusResponse.last_sync_time:type_name -> google.protobuf.Timestamp
	0,  // 8: keyper.api.v1.Conflict.type:type_name -> keyper.api.v1.ConflictType
	9,  // 9: keyper.api.v1.Conflict.server_version:type_name -> keyper.api.v1.Secret
	9,  // 10: keyper.api.v1.Conflict.client_version:type_name -> keyper.api.v1.Secret
	1,  // 11: keyper.api.v1.SyncService.Pull:input_type -> keyper.api.v1.PullRequest
	3,  // 12: keyper.api.v1.SyncService.Push:input_type -> keyper.api.v1.PushRequest
	5,  // 13: keyper.api.v1.SyncService.GetSyncStatus:input_type -> keyper.api.v1.GetSyncStatusRequest
	2,  // 14: keyper.api.v1.SyncService.Pull:output_type -> keyper.api.v1.PullResponse
	4,  // 15: keyper.api.v1.SyncService.Push:output_type -> keyper.api.v1.PushResponse
	6,  // 16: keyper.api.v1.SyncService.GetSyncStatus:output_type -> keyper.api.v1.GetSyncStatusResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	file_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		EnumInfos:         file_sync_proto_enumTypes,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
